version: '2'
services:
    app:
        build: .
        image: go-shortener
        environment:
            - REDIS_URL=redis:6379
        volumes:
            - .:/go/src/app
            - ./public:/usr/local/web
        ports:
            - "8080:8080"
        links:
            - redis
    redis:
        image: redis
